Updated to fix loading existing bash file

diff --git a/dependency-manager b/dependency-manager
--- a/dependency-manager
+++ b/dependency-manager
@@ -32,14 +32,13 @@ __loadDependencies()
         repoName=${dependencyRec[1]}
         releaseTag=${dependencyRec[2]}
         fileName=${dependencyRec[3]}
-        if [ -f "lib/${fileName}" ]; then
-            continue
-        fi        
-        echo "Loading dependency: ${fileName}"
-        __getFileFromGitRepo "${repoOwner}" "${repoName}" "${releaseTag}" "${fileName}" "${saveDirectory}" 
-        if (( $? )); then
-            echo "Failed to retrieve dependency: ${fileName}.  Aborting..."
-            exit 1
+        if [ ! -f "lib/${fileName}" ]; then    
+            echo "Loading dependency: ${fileName}"
+            __getFileFromGitRepo "${repoOwner}" "${repoName}" "${releaseTag}" "${fileName}" "${saveDirectory}" 
+            if (( $? )); then
+                echo "Failed to retrieve dependency: ${fileName}.  Aborting..."
+                exit 1
+            fi
         fi
         source "lib/${fileName}"
     done < dependencies.list  
